name: deblurgan
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.0=py36_0
  - astor=0.8.0=py36_0
  - astroid=2.3.2=py36_0
  - attrs=19.3.0=py_0
  - autopep8=1.4.4=py_0
  - backcall=0.1.0=py36_0
  - blas=2.14=openblas
  - bleach=3.1.0=py36_0
  - bzip2=1.0.8=h516909a_1
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2019.10.16=0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.9.11=py36_0
  - click=7.0=py_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.0=cuda10.0_0
  - cupti=10.0.130=0
  - cycler=0.10.0=py36_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.1.3=h167e202_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py36_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.1.9=h516909a_0
  - glib=2.58.3=h6f030ca_1002
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.6.5=hd3a4fd2_1002
  - google-pasta=0.1.7=py_0
  - graphite2=1.3.13=hf484d3e_1000
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - h5py=2.10.0=nompi_py36h513d04c_100
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - importlib_metadata=0.23=py36_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.3=py36h39e3cac_0
  - ipython=7.9.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py36_0
  - jasper=1.900.1=h07fcdf6_1006
  - jedi=0.15.1=py36_0
  - jinja2=2.10.3=py_0
  - joblib=0.13.2=py36_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.1.1=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.3.4=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.6.1=py36_0
  - keras=2.2.4=0
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py36_0
  - keras-gpu=2.2.4=0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py36he6710b0_0
  - lame=3.100=h14c3975_1001
  - lazy-object-proxy=1.4.2=py36h7b6447c_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=9.0.0=hc9558a2_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_openblas
  - liblapacke=3.8.0=14_openblas
  - libllvm9=9.0.0=hc9558a2_2
  - libopenblas=0.3.7=h6e990d7_2
  - libopencv=4.1.2=h6185dc4_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.9.2=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=hfc65ed5_1004
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h576950b_1
  - libxcb=1.13=h1bed415_1
  - libxkbcommon=0.9.1=hebb1f50_0
  - libxml2=2.9.9=hea5a465_1
  - lz4-c=1.8.3=he1b5a44_1001
  - markdown=3.1.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.1=py36_1
  - matplotlib-base=3.1.1=py36he7580a8_1
  - mccabe=0.6.1=py36_1
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36h516909a_1
  - mkl_random=1.1.0=py36hb3f55d8_0
  - more-itertools=7.2.0=py36_0
  - nbconvert=5.6.1=py36_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.4.1=h1bed415_1002
  - notebook=6.0.1=py36_0
  - nspr=4.23=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.17.3=py36h95a1406_0
  - numpy-base=1.17.2=py36h2f8d375_0
  - olefile=0.46=py36_0
  - opencv=4.1.2=0
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1=h7b6447c_0
  - opt_einsum=3.1.0=py_0
  - pandas=0.25.2=py36he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.5.1=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=6.2.0=py36h34e0f95_0
  - pip=19.3.1=py36_0
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - protobuf=3.9.2=py36he6710b0_0
  - ptyprocess=0.6.0=py36_0
  - py-opencv=4.1.2=py36h5ca1d4c_0
  - pycodestyle=2.5.0=py36_0
  - pygments=2.4.2=py_0
  - pylint=2.4.3=py36_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.12.3=py36hcca6a23_0
  - pyrsistent=0.15.4=py36h7b6447c_0
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.3=py_0
  - pyyaml=5.1.2=py36h7b6447c_0
  - pyzmq=18.1.0=py36he6710b0_0
  - qt=5.12.5=hd8c4c69_1
  - qtconsole=4.5.5=py_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.21.3=py36hcdab131_0
  - scipy=1.3.1=py36h921218d_2
  - send2trash=1.5.0=py36_0
  - setuptools=41.6.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - sqlite=3.30.1=h7b6447c_0
  - tensorboard=2.0.0=pyhb230dea_0
  - tensorflow=2.0.0=gpu_py36h6b29c10_0
  - tensorflow-base=2.0.0=gpu_py36h0ec5d1f_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - tensorflow-gpu=2.0.0=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py36_0
  - tk=8.6.9=hed695b0_1003
  - tornado=6.0.3=py36h7b6447c_0
  - tqdm=4.36.1=py_0
  - traitlets=4.3.3=py36_0
  - typed-ast=1.4.0=py36h7b6447c_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - wrapt=1.11.2=py36h7b6447c_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.3=h3b9ef0a_0
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: /home/siddhant/anaconda3/envs/deblurgan

